### ISSUE TITLE
Use AWS Profile on the local development environment rather than key/secret?

### ISSUE THREAD

**Issue by EdsonF** [camitz/CloudWatchAppender#26]
Is it possible to use AWS Profile on the local development environment rather than key/secret?

Thanks for your help

**Comment by idlem1nd** [comment]
I'd also like to know if this is possible... the readme hints that this is possible:

> Note In the above example credentials is in clear text and this is not the Amazon recommended way of doing things. See Configuring Credentials and End Point.

But that section is empty...

**Comment by idlem1nd** [comment]
But then again, based on [this](https://github.com/camitz/CloudWatchAppender/issues/2) maybe it works just by leaving `accessKey` and `secret` empty?

**Comment by camitz** [comment]
Sorry for not replying sooner! Yes, this works. I believe at least one of
the samples is set up this way. I'll get back to you with a more
comprehensive answer and possibly even update the doc!

ons 21 juni 2017 kl. 16:34 skrev idlem1nd <notifications@github.com>:

**Comment by idlem1nd** [comment]
Thanks if you could help - I can only get it to work by specifying the accessKey and secret. If I miss  those out, the `XmlConfigurator.Configure` method in log4net throws a `CloudWatchAppenderException` at startup, "Couldn't create Amazon client"

```
   at CloudWatchAppender.Services.CloudWatchClientWrapperBase`1.SetupClient(ClientConfig clientConfig) in c:\projects\cloudwatchappender\CloudWatchAppender\Services\CloudWatchClientWrapperBase.cs:line 105
   at CloudWatchAppender.Services.CloudWatchClientWrapperBase`1..ctor(String endPoint, String accessKey, String secret, ClientConfig clientConfig) in c:\projects\cloudwatchappender\CloudWatchAppender\Services\CloudWatchClientWrapperBase.cs:line 32
   at CloudWatchAppender.Services.CloudWatchLogsClientWrapper..ctor(String endPoint, String accessKey, String secret, ClientConfig clientConfig) in c:\projects\cloudwatchappender\CloudWatchAppender\Services\CloudWatchLogsClientWrapper.cs:line 18
   at CloudWatchAppender.BufferingCloudWatchLogsAppender.ActivateOptions() in c:\projects\cloudwatchappender\CloudWatchAppender\BufferingCloudWatchLogsAppender.cs:line 130
   at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.ParseAppender(XmlElement appenderElement)
```

**Comment by camitz** [comment]
You seem to be using an old version. What version are you using?

**Comment by idlem1nd** [comment]
@camitz I'm using the latest version from NuGet - 4.7.0.6
